Repository Changes:
  - ./*
    
Libraries Changes:
  - libs/*
    
Core Changes:
  - hbogolib/*
    
Eu regional handler changes:
  - hbogolib/handlereu.py
    
Nordic/Spain regional handler changes:
  - hbogolib/handlersp.py
    
GitHub Config Changes:
  - .github/**/*

Translation: resources/language/**/*

Add-on settings: resources/settings.xml
